# HTTP Server configurations.
[server]
	Address        = ":8199"
	ServerRoot     = "public"
	RouteOverWrite = true

# Logger configurations.
[logger]
    Path   = "/tmp/log/gf-alpha"
    Level  = "all"
    Stdout = true

# View configurations.
# 模板引擎配置
[viewer]
    defaultFile = "layout/default.html"

# Database configurations.
[database]
    Link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/gf"
    Debug = true
