# Web Server.
[server]
	Address        = ":8199"
	ServerRoot     = "public"
	RouteOverWrite = true

# 文件上传设置
[upload]
    path = "upload"

# 日志配置
[logger]
    Path   = "/tmp/log/focus"
    Level  = "all"
    Stdout = true

# 模板引擎配置
[viewer]
    Delimiters  =  ["${", "}"]
    DefaultFile = "web/layout/layout.html"

# 数据库配置
[database]
    Link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/gf"
    Debug = true
