# HTTP Server configurations.
[server]
	Address        = ":8199"
	ServerRoot     = "public"
	RouteOverWrite = true

# Logger configurations.
[logger]
    Path   = "/tmp/log/gf-alpha"
    Level  = "all"
    Stdout = true

# 模板引擎配置
[viewer]
    delimiters  =  ["${", "}"]
    [viewer.admin]
        Path        = "template"
        DefaultFile = "index.html"

# Database configurations.
[database]
    Link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/gf"
    Debug = true
